version: '3.8'

services:
  oisexam-postgres:
    container_name: oisexam-postgres
    image: postgres:latest
    restart: on-failure
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - "5435:5432"
    volumes:
      - oisexam-postgres-volume:/var/lib/postgresql/data
volumes:
  oisexam-postgres-volume: